default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  socket: /tmp/mysql.sock
  database: draft

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  username: mlii
  password: <%= ENV['prod_mysql_pass'] %>
  socket: /var/lib/mysql/mysql.sock