default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  socket: /tmp/mysql.sock
  database: draft

development:
  <<: *default
test:
  <<: *default

production:
  adapter: mysql2
  database: <%= ENV['sql_db'] %>
  encoding: utf8
  username: <%= ENV['sql_user'] %>
  password: <%= ENV['sql_pass'] %>
  socket:  <%= ENV['sql_socket'] %>
